# Generated by Django 5.2.4 on 2025-09-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='company_details',
            field=models.TextField(blank=True, help_text='Detailed information about your company, mission, and team.', null=True),
        ),
    ]
