# Generated by Django 5.2.4 on 2025-09-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entrepreneurprofile_company_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='company_logo',
            field=models.ImageField(blank=True, help_text="Upload your company's logo.", null=True, upload_to='company_logos/'),
        ),
    ]
